task2
pvordgh/phptest pull request #3
Opened 2021-11-05 15:33 UTC by pvordgh

2021-11-05 15:42 UTC, ckomarov requested changes

2021-11-05 15:42 UTC, ckomarov commented on task2.php
> +$arr=['a', 'b', 'c'];
code style (check PSR-12)
need spaces before and after =

2021-11-05 15:42 UTC, ckomarov commented on task2.php
> +var_dump($arr);
use var_dump only for debuggig purpose, don't push it

2021-11-05 15:42 UTC, ckomarov commented on task2.php
> +$arr=['a', 'b', 'c', 'd'];
code style

2021-11-05 15:42 UTC, ckomarov commented on task2.php
> +echo $arr[0].'+'.$arr[1].', '.$arr[2].'+'.$arr[3].'<br>';
code style (spaces around '.')

2021-11-05 15:42 UTC, ckomarov commented on task2.php
> +$arr=[2, 5, 3, 9];
code style

2021-11-05 15:42 UTC, ckomarov commented on task2.php
> +$array[] = 1;
use a loop to push elements to array

2021-11-05 15:42 UTC, ckomarov commented on task2.php
> +?>
don't use this

2021-11-08 15:34 UTC, ckomorov approved these changes
done.

2021-11-10 09:22 UTC, merged